import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_contexts/CartContextProvider";
import { getLoggedUser } from "./_actions/cart.Action";
import { getLoggedUserWhishlist } from "./_actions/whishlist.Actions";
import Footer from "./_components/Footer";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userCart = await getLoggedUser()
  const userWishlist = await getLoggedUserWhishlist()


  return (
    
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

    <MySessionProvider>

      <CartContextProvider userCart = {userCart} userWishlist={userWishlist}>
        <>
          <Toaster/>
          <Navbar/>
          {children}
          <Footer/>
        </>

      </CartContextProvider>

    </MySessionProvider>



        
      </body>
    </html>
  );
}
